apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-data-deployment
  labels:
    app: mongo-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-data
  template:
    metadata:
      labels:
        app: mongodb-data
    spec:
      containers:
      - name: mongodb-data
        image: mongo:8
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-data-service
spec:
  selector:
    app: mongodb-data
  ports:
  - port: 27017