apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-analysis-deployment
  labels:
    app: weather-analysis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-analysis
  template:
    metadata:
      labels:
        app: weather-analysis
    spec:
      containers:
      - name: weather-analysis
        image: weather-analysis:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: FLASK_SERVER_PORT
          value: "9091"
        ports:
        - containerPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: weather-analysis-service
spec:
  type: NodePort
  selector:
    app: weather-analysis
  ports:
  - port: 9091
    targetPort: 9091
